tosca_definitions_version: alien_dsl_1_4_0

metadata:
  template_name: org.alien4cloud.automation.a4c.config.orchestrator.conf_cfy_azure
  template_version: 1.4.0-SNAPSHOT
  template_author: alien4cloud

imports:
  - alien-base-types:1.4.0
  - org.alien4cloud.automation.a4c.config.pub:1.4.0-SNAPSHOT
  - org.alien4cloud.automation.a4c.config.orchestrator.cfy:1.4.0-SNAPSHOT
  - tosca-normative-types:1.0.0-ALIEN14

node_types:

  org.alien4cloud.automation.a4c.config.orchestrator.cfy.nodes.CfyAzureParametersConfigurator:
    description: |
      Configure azure parameters for cfy orchestrator
    derived_from: org.alien4cloud.automation.a4c.config.orchestrator.cfy.nodes.CfyOrchestratorConfigurator
    properties:
      resourceGroupId:
        type: string
        required: true
      virtualNetworkId:
        type: string
        required: true
      subnetId:
        type: string
        required: true

    interfaces:
      Standard:
        start:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: config_azure_parameters.yml
            orchestratorId: { get_attribute: [SELF, orchestratorId] }
            alien_url: { get_attribute: [SELF, alien_url] }
            alien_user: { get_attribute: [SELF, alien_user] }
            alien_password: { get_attribute: [SELF, alien_password] }
            resourceGroup: { get_property: [SELF, resourceGroupId] }
            virtualNetwork: { get_property: [SELF, virtualNetworkId] }
            subnet: { get_property: [SELF, subnetId] }
          implementation: playbook/playbook.ansible
