tosca_definitions_version: alien_dsl_1_4_0

metadata:
  template_name: org.alien4cloud.mock.ansible
  template_version: 2.0.0-SNAPSHOT
  template_author: alien4cloud

imports:
  - tosca-normative-types:1.0.0-ALIEN14
  - alien-base-types:1.4.0
  - org.alien4cloud.mock.pub:2.0.0-SNAPSHOT

description: >
  Mock types for A4C load tests.

node_types:

  org.alien4cloud.mock.ansible.nodes.AnsibleMockHost:
    description: |
      A software component that hosts MockComponent.
    derived_from: org.alien4cloud.mock.pub.nodes.AbstractMockHost
    interfaces:
      Standard:
        create:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: operation.yml
            operation: "create AnsibleMockHost"
            duration: { get_property: [ SELF, duration ] }
            variation: { get_property: [ SELF, variation ] }
            weight: 50
            log_length: { get_property: [ SELF, log_length ] }
          implementation: playbook/playbook.ansible
        configure:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: operation.yml
            operation: "configure AnsibleMockHost"
            duration: { get_property: [ SELF, duration ] }
            variation: { get_property: [ SELF, variation ] }
            weight: 30
            sleep_factor: { get_property: [ SELF, sleep_factor ] }
            log_length: { get_property: [ SELF, log_length ] }
          implementation: playbook/playbook.ansible
        start:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: operation.yml
            operation: "start AnsibleMockHost"
            duration: { get_property: [ SELF, duration ] }
            variation: { get_property: [ SELF, variation ] }
            weight: 20
            log_length: { get_property: [ SELF, log_length ] }
          implementation: playbook/playbook.ansible
        # stop:
        #   inputs:
        #     ANSIBLE_VERBOSE: false
        #     PLAYBOOK_ENTRY: operation.yml
        #     operation: "stop AnsibleMockHost"
        #     sleep_time: 2
        #     sleep_factor: { get_property: [ SELF, sleep_factor ] }
        #     log_length: { get_property: [ SELF, log_length ] }
        #   implementation: playbook/playbook.ansible
        # delete:
        #   inputs:
        #     ANSIBLE_VERBOSE: false
        #     PLAYBOOK_ENTRY: operation.yml
        #     operation: "delete AnsibleMockHost"
        #     sleep_time: 2
        #     sleep_factor: { get_property: [ SELF, sleep_factor ] }
        #     log_length: { get_property: [ SELF, log_length ] }
        #   implementation: playbook/playbook.ansible
  org.alien4cloud.mock.ansible.nodes.AnsibleMockComponent:
    description: |
      A software component hosted on GenericHost and that can connect to many other Generic.
    derived_from: org.alien4cloud.mock.pub.nodes.AbstractMockComponent
    capabilities:
      mock_endpoint:
        type: org.alien4cloud.mock.ansible.capabilities.AnsibleComponentEndpoint
        occurrences: [0, unbounded]
    requirements:
      - host:
          capability: tosca.capabilities.Container
          relationship: org.alien4cloud.mock.ansible.relationships.AnsibleComponentHostedOnHost
          occurrences: [1,1]
      - mock_endpoint:
          capability: org.alien4cloud.mock.ansible.capabilities.AnsibleComponentEndpoint
          relationship: org.alien4cloud.mock.ansible.relationships.AnsibleComponentConnectToComponent
          occurrences: [0, unbounded]
    interfaces:
      Standard:
        create:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: operation.yml
            operation: "create AnsibleMockComponent"
            duration: { get_property: [ SELF, duration ] }
            variation: { get_property: [ SELF, variation ] }
            weight: 50
            log_length: { get_property: [ SELF, log_length ] }
          implementation: playbook/playbook.ansible
        configure:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: operation.yml
            operation: "configure AnsibleMockComponent"
            duration: { get_property: [ SELF, duration ] }
            variation: { get_property: [ SELF, variation ] }
            weight: 30
            log_length: { get_property: [ SELF, log_length ] }
          implementation: playbook/playbook.ansible
        start:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: operation.yml
            operation: "start AnsibleMockComponent"
            duration: { get_property: [ SELF, duration ] }
            variation: { get_property: [ SELF, variation ] }
            weight: 20
            log_length: { get_property: [ SELF, log_length ] }
          implementation: playbook/playbook.ansible
        # stop:
        #   inputs:
        #     ANSIBLE_VERBOSE: false
        #     PLAYBOOK_ENTRY: operation.yml
        #     operation: "stop AnsibleMockComponent"
        #     sleep_time: 2
        #     sleep_factor: { get_property: [ SELF, sleep_factor ] }
        #     log_length: { get_property: [ SELF, log_length ] }
        #   implementation: playbook/playbook.ansible
        # delete:
        #   inputs:
        #     ANSIBLE_VERBOSE: false
        #     PLAYBOOK_ENTRY: operation.yml
        #     operation: "delete AnsibleMockComponent"
        #     sleep_time: 2
        #     sleep_factor: { get_property: [ SELF, sleep_factor ] }
        #     log_length: { get_property: [ SELF, log_length ] }
        #   implementation: playbook/playbook.ansible

relationship_types:

  org.alien4cloud.mock.ansible.relationships.AnsibleComponentHostedOnHost:
    derived_from: org.alien4cloud.mock.pub.relationships.AbstractComponentHostedOnHost
    valid_target_types: [ org.alien4cloud.mock.ansible.nodes.AnsibleMockHost ]
    interfaces:
      configure:
        pre_configure_source:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: operation.yml
            operation: "pre_configure_source AnsibleComponentHostedOnHost"
            duration: 2
            variation: { get_property: [ SOURCE, variation ] }
            weight: 30
            log_length: { get_property: [ SOURCE, log_length ] }
          implementation: playbook/playbook.ansible
        pre_configure_target:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: operation.yml
            operation: "pre_configure_target AnsibleComponentHostedOnHost"
            duration: 2
            variation: { get_property: [ SOURCE, variation ] }
            weight: 30
            log_length: { get_property: [ SOURCE, log_length ] }
          implementation: playbook/playbook.ansible
        post_configure_source:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: operation.yml
            operation: "post_configure_source AnsibleComponentHostedOnHost"
            duration: 2
            variation: { get_property: [ SOURCE, variation ] }
            weight: 30
            log_length: { get_property: [ SOURCE, log_length ] }
          implementation: playbook/playbook.ansible
        post_configure_target:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: operation.yml
            operation: "post_configure_target AnsibleComponentHostedOnHost"
            duration: 2
            variation: { get_property: [ SOURCE, variation ] }
            weight: 30
            log_length: { get_property: [ SOURCE, log_length ] }
          implementation: playbook/playbook.ansible
        add_target:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: operation.yml
            operation: "add_target AnsibleComponentHostedOnHost"
            duration: 2
            variation: { get_property: [ SOURCE, variation ] }
            weight: 30
            log_length: { get_property: [ SOURCE, log_length ] }
          implementation: playbook/playbook.ansible
        add_source:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: operation.yml
            operation: "add_source AnsibleComponentHostedOnHost"
            duration: 2
            variation: { get_property: [ SOURCE, variation ] }
            weight: 30
            log_length: { get_property: [ SOURCE, log_length ] }
          implementation: playbook/playbook.ansible
        # remove_target:
        #   inputs:
        #     ANSIBLE_VERBOSE: false
        #     PLAYBOOK_ENTRY: operation.yml
        #     operation: "remove_target AnsibleComponentHostedOnHost"
        #     sleep_time: 5
        #     sleep_factor: { get_property: [ SOURCE, sleep_factor ] }
        #     log_length: { get_property: [ SOURCE, log_length ] }
        #   implementation: playbook/playbook.ansible
        # remove_source:
        #   inputs:
        #     ANSIBLE_VERBOSE: false
        #     PLAYBOOK_ENTRY: operation.yml
        #     operation: "remove_source AnsibleComponentHostedOnHost"
        #     sleep_time: 5
        #     sleep_factor: { get_property: [ SOURCE, sleep_factor ] }
        #     log_length: { get_property: [ SOURCE, log_length ] }
        #   implementation: playbook/playbook.ansible
  org.alien4cloud.mock.ansible.relationships.AnsibleComponentConnectToComponent:
    derived_from: org.alien4cloud.mock.pub.relationships.AbstractComponentConnectToComponent
    valid_target_types: [ org.alien4cloud.mock.ansible.capabilities.AnsibleComponentEndpoint ]
    interfaces:
      configure:
        pre_configure_source:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: operation.yml
            operation: "pre_configure_source AnsibleComponentConnectToComponent"
            duration: 2
            variation: { get_property: [ SOURCE, variation ] }
            weight: 30
            log_length: { get_property: [ SOURCE, log_length ] }
          implementation: playbook/playbook.ansible
        pre_configure_target:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: operation.yml
            operation: "pre_configure_target AnsibleComponentConnectToComponent"
            duration: 2
            variation: { get_property: [ SOURCE, variation ] }
            weight: 30
            log_length: { get_property: [ SOURCE, log_length ] }
          implementation: playbook/playbook.ansible
        post_configure_source:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: operation.yml
            operation: "post_configure_source AnsibleComponentConnectToComponent"
            duration: 2
            variation: { get_property: [ SOURCE, variation ] }
            weight: 30
            log_length: { get_property: [ SOURCE, log_length ] }
          implementation: playbook/playbook.ansible
        post_configure_target:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: operation.yml
            operation: "post_configure_target AnsibleComponentConnectToComponent"
            duration: 2
            variation: { get_property: [ SOURCE, variation ] }
            weight: 30
            log_length: { get_property: [ SOURCE, log_length ] }
          implementation: playbook/playbook.ansible
        add_target:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: operation.yml
            operation: "add_target AnsibleComponentConnectToComponent"
            duration: 2
            variation: { get_property: [ SOURCE, variation ] }
            weight: 30
            log_length: { get_property: [ SOURCE, log_length ] }
          implementation: playbook/playbook.ansible
        add_source:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: operation.yml
            operation: "add_source AnsibleComponentConnectToComponent"
            duration: 2
            variation: { get_property: [ SOURCE, variation ] }
            weight: 30
            log_length: { get_property: [ SOURCE, log_length ] }
          implementation: playbook/playbook.ansible
        # remove_target:
        #   inputs:
        #     ANSIBLE_VERBOSE: false
        #     PLAYBOOK_ENTRY: operation.yml
        #     operation: "remove_target AnsibleComponentConnectToComponent"
        #     sleep_time: 5
        #     sleep_factor: { get_property: [ SOURCE, sleep_factor ] }
        #     log_length: { get_property: [ SOURCE, log_length ] }
        #   implementation: playbook/playbook.ansible
        # remove_source:
        #   inputs:
        #     ANSIBLE_VERBOSE: false
        #     PLAYBOOK_ENTRY: operation.yml
        #     operation: "remove_source AnsibleComponentConnectToComponent"
        #     sleep_time: 5
        #     sleep_factor: { get_property: [ SOURCE, sleep_factor ] }
        #     log_length: { get_property: [ SOURCE, log_length ] }
        #   implementation: playbook/playbook.ansible

capability_types:
  org.alien4cloud.mock.ansible.capabilities.AnsibleComponentEndpoint:
    derived_from: org.alien4cloud.mock.pub.capabilities.AbstractComponentEndpoint
