tosca_definitions_version: alien_dsl_1_4_0

metadata:
  template_name: org.alien4cloud.monitoring.grafana
  template_version: 1.4.0-SNAPSHOT
  template_author: alien4cloud

imports:
  - tosca-normative-types:1.0.0-ALIEN14
  - alien-base-types:1.4.0
  - org.alien4cloud.monitoring.graphite:1.4.0-SNAPSHOT
  - org.alien4cloud.monitoring.pub:1.4.0-SNAPSHOT

node_types:

  org.alien4cloud.monitoring.grafana.nodes.Grafana:
    derived_from: org.alien4cloud.monitoring.pub.nodes.GrafanaService
    metadata:
      icon: /images/grafana.png
    description: |
      Grafana frontend
    properties:
      component_version:
        type: version
        default: 4.1.2
        constraints:
          - valid_values: [ "4.1.2" ]
    attributes:
      grafana_url: { concat: ["http://", get_attribute: [ SELF, public_ip_address ], ":", get_property: [ SELF, http_endpoint, port ]]}
    capabilities:
      http_endpoint:
        type: org.alien4cloud.monitoring.pub.capabilities.GrafanaHttpEndpoint
        occurrences: [0, UNBOUNDED]
        description: UI endpoint
        properties:
          protocol: http
          port: 3000 # set a default value for the port
          user: admin
          password: admin
    requirements:
      - host: # Overrides the parent host requirement to add a specific node_filter and add OS constraints as Impl is based on yum and so restricted to centos.
          capability: tosca.capabilities.Container
          node: tosca.nodes.Compute
          relationship: tosca.relationships.HostedOn
          occurrences: [1, 1]
          node_filter:
            capabilities:
              - tosca.capabilities.OperatingSystem:
                  properties:
                    - type: { equal: linux }
                    - architecture: { equal: x86_64 }
                    - distribution: { valid_values: [ "red hat", "centos", "rhel" ] }
      - graphite:
          capability: org.alien4cloud.monitoring.pub.capabilities.GraphiteHttpEndpoint
          relationship: org.alien4cloud.monitoring.grafana.relationships.GrafanaConnectToGraphite
          occurrences: [0, UNBOUNDED]
      # - graphite:
      #     capability: org.alien4cloud.monitoring.pub.capabilities.GraphiteHttpEndpoint
      #     relationship: org.alien4cloud.monitoring.grafana.relationships.GrafanaConnectToGraphite
      #     occurrences: [0, UNBOUNDED]

    interfaces:
      Standard:
        create:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: create.yml
          implementation: playbook/playbook.ansible
        start:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: start.yml
          implementation: playbook/playbook.ansible
        stop:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: stop.yml
          implementation: playbook/playbook.ansible
        delete:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: delete.yml
          implementation: playbook/playbook.ansible


relationship_types:

  # org.alien4cloud.monitoring.grafana.relationships.GrafanaConnectToBackend:
  #   derived_from: tosca.relationships.ConnectsTo
  #   abstract: true
  #   valid_target_types: [ org.alien4cloud.monitoring.pub.nodes.MetricsBackend ]
  org.alien4cloud.monitoring.grafana.relationships.GrafanaConnectToGraphite:
    derived_from: tosca.relationships.ConnectsTo
    # derived_from: tosca.relationships.ConnectsTo
    properties:
      datasource_name:
        type: string
        required: true
        default: Graphite_DS
    valid_target_types: [ org.alien4cloud.monitoring.pub.capabilities.GraphiteHttpEndpoint ]
    interfaces:
      Configure:
        add_target:
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: connects_to_graphite.yml
            graphite_host: { get_attribute: [TARGET, http_endpoint, ip_address] }
            graphite_port: { get_property: [TARGET, http_endpoint, port]}
            grafana_port: { get_property: [SOURCE, http_endpoint, port]}
            grafana_user: { get_property: [SOURCE, http_endpoint, user]}
            grafana_password: { get_property: [SOURCE, http_endpoint, password]}
            datasource_name: { get_property: [SELF, datasource_name]}
          implementation: playbook/playbook.ansible
