tosca_definitions_version: alien_dsl_1_4_0

metadata:
  template_name: org.alien4cloud.automation.a4c.config.location_resources.autoconfig
  template_version: 1.4.0-SNAPSHOT
  template_author: alien4cloud

imports:
  - alien-base-types:1.4.0
  - org.alien4cloud.automation.a4c.config.location:1.4.0-SNAPSHOT
  - org.alien4cloud.automation.cloudify.hostpool.pub:1.4.0-SNAPSHOT
  - tosca-normative-types:1.0.0-ALIEN14

node_types:

  org.alien4cloud.automation.a4c.config.location_resources.autoconfig.nodes.ResourcesConfigurator:
    description: |
      Configure a location for A4C, resources are fed using a resource yaml file
    derived_from: org.alien4cloud.automation.a4c.config.location.nodes.SimpleLocationConfigurator
    artifacts:
      - resources_file_artifact:
          type: tosca.artifacts.File
    interfaces:
      Standard:
        start:
          # create the location on demand resources
          inputs:
            ANSIBLE_VERBOSE: false
            PLAYBOOK_ENTRY: create_location_resources.yml
            orchestratorId: { get_attribute: [HOST, orchestratorId] }
            locationId: { get_attribute: [SELF, locationId] }
            alien_url: { get_attribute: [HOST, alien_url] }
            alien_user: { get_attribute: [HOST, alien_user] }
            alien_password: { get_attribute: [HOST, alien_password] }
          implementation: playbook/playbook.ansible
